/**
 * Repro Test Generator — Creates Playwright Electron tests from detected issues.
 *
 * For each issue in issues.json, generates a standalone test file at
 * tests/repro/ISS-{id}.spec.ts that reproduces the issue.
 */

import path from 'path';
import fs from 'fs';
import type { Issue, CrawlConfig } from './types.js';

/**
 * Generate repro tests for all issues (or a specific one).
 */
export function generateReproTests(
  issues: Issue[],
  config: CrawlConfig,
  targetIssueId?: string
): { generated: number; skipped: number } {
  const testsDir = path.join(config.projectRoot, 'tools', 'crawler', 'tests', 'repro');
  fs.mkdirSync(testsDir, { recursive: true });

  let generated = 0;
  let skipped = 0;

  const toGenerate = targetIssueId
    ? issues.filter(i => i.id === targetIssueId)
    : issues;

  for (const issue of toGenerate) {
    // Only generate for error and critical severity
    if (issue.severity === 'warning') {
      skipped++;
      continue;
    }

    const testCode = buildTestCode(issue, config);
    const fileName = `${issue.id}.spec.ts`;
    const filePath = path.join(testsDir, fileName);

    fs.writeFileSync(filePath, testCode);
    generated++;

    console.log(`[ReproGen] Generated: ${fileName} — ${issue.title}`);
  }

  return { generated, skipped };
}

/**
 * Build the Playwright test code for a single issue.
 */
function buildTestCode(issue: Issue, config: CrawlConfig): string {
  const projectRoot = config.projectRoot.replace(/'/g, "\\'");
  const electronPath = config.electronPath.replace(/'/g, "\\'");

  // Build navigation steps
  const navSteps = buildNavigationSteps(issue);

  // Build assertion
  const assertion = buildAssertion(issue);

  return `/**
 * Auto-generated repro test for ${issue.id}
 *
 * ${issue.title}
 * Severity: ${issue.severity}
 * Category: ${issue.category}
 * Route: ${issue.route}
 *
 * Generated by TC Crawler on ${new Date().toISOString().slice(0, 10)}
 */

import { test, expect, _electron } from '@playwright/test';

test('${issue.id}: ${issue.title.replace(/'/g, "\\'")}', async () => {
  // Launch app in mock mode
  const electronApp = await _electron.launch({
    executablePath: '${electronPath}',
    args: ${JSON.stringify(electronPath.includes('.app/') ? [] : [projectRoot])},
    env: {
      ...process.env,
      MOCK_EXTERNAL: 'true',
      SAFE_MODE: 'true',
      FUB_API_KEY: '',
      ANTHROPIC_API_KEY: '',
    },
    timeout: 30_000,
  });

  const page = await electronApp.firstWindow();

  // Wait for app to initialize
  await page.waitForSelector('#root', { timeout: 15_000 });
  await page.waitForTimeout(2000);

${navSteps}

${assertion}

  await electronApp.close();
});
`;
}

/**
 * Build navigation steps based on the issue's route and repro steps.
 */
function buildNavigationSteps(issue: Issue): string {
  const steps: string[] = [];

  // Navigate to the route
  if (issue.route && issue.route !== '/' && issue.route !== 'N/A' && issue.route !== 'various') {
    steps.push(`  // Navigate to ${issue.route}`);
    steps.push(`  await page.evaluate(() => { window.location.hash = '#${issue.route}'; });`);
    steps.push(`  await page.waitForTimeout(2000);`);
  }

  // Add any explicit repro steps
  if (issue.reproSteps && issue.reproSteps.length > 0) {
    steps.push(`  // Repro steps:`);
    for (const step of issue.reproSteps) {
      steps.push(`  // - ${step}`);
    }
  }

  return steps.join('\n');
}

/**
 * Build assertion code based on the issue category and type.
 */
function buildAssertion(issue: Issue): string {
  switch (issue.category) {
    case 'ui':
      if (issue.title.includes('Blank screen')) {
        return `  // Verify the page renders content (not blank)
  const rootChildren = await page.locator('#root').evaluate(el => el.children.length);
  expect(rootChildren).toBeGreaterThan(0);

  // Verify visible text content exists
  const textContent = await page.locator('#root').textContent();
  expect(textContent?.length).toBeGreaterThan(0);`;
      }
      if (issue.title.includes('dead click')) {
        return `  // Verify the element is interactive
  // (Manual inspection needed for dead click issues)
  const page_loaded = await page.locator('#root').evaluate(el => el.children.length > 0);
  expect(page_loaded).toBe(true);`;
      }
      return `  // Verify no error UI is shown
  const errorBoundary = await page.$('[data-testid="error-boundary"]');
  expect(errorBoundary).toBeNull();`;

    case 'renderer':
      if (issue.title.includes('Uncaught exception')) {
        return `  // Verify no uncaught exceptions
  const errors: string[] = [];
  page.on('pageerror', (err) => errors.push(err.message));

  // Trigger the page that caused the error
  await page.waitForTimeout(3000);

  expect(errors).toHaveLength(0);`;
      }
      return `  // Verify no console errors
  const consoleErrors: string[] = [];
  page.on('console', (msg) => {
    if (msg.type() === 'error') consoleErrors.push(msg.text());
  });

  await page.waitForTimeout(3000);

  // Filter out known noise
  const realErrors = consoleErrors.filter(e =>
    !e.includes('DevTools') && !e.includes('favicon') && !e.includes('net::ERR_')
  );
  expect(realErrors).toHaveLength(0);`;

    case 'ipc':
      return `  // Verify IPC call succeeds
  // Channel: ${issue.ipcChannel || 'unknown'}
  const result = await page.evaluate(async () => {
    try {
      const api = (window as any).electronAPI;
      // Attempt the IPC call that failed
      return { success: true };
    } catch (err: any) {
      return { success: false, error: err.message };
    }
  });

  expect(result.success).toBe(true);`;

    case 'main':
      return `  // Verify main process is stable
  const isRunning = electronApp.process().exitCode === null;
  expect(isRunning).toBe(true);

  // Wait for potential delayed errors
  await page.waitForTimeout(5000);

  // Process should still be running
  expect(electronApp.process().exitCode).toBeNull();`;

    default:
      return `  // Generic assertion — issue needs manual inspection
  // ${issue.title}
  const pageLoaded = await page.locator('#root').evaluate(el => el.children.length > 0);
  expect(pageLoaded).toBe(true);`;
  }
}
